# Generated by Django 5.2.5 on 2025-08-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volunteer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('skills', models.TextField(blank=True, verbose_name='Skills & Experience')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='Availability')),
                ('is_onboarded', models.BooleanField(default=False, verbose_name='Onboarding Complete')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='associated_people',
            field=models.ManyToManyField(blank=True, related_name='associated_cases', to='api.person'),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_cases', to='api.person'),
        ),
        migrations.AddField(
            model_name='referralmedia',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.case'),
        ),
        migrations.AddField(
            model_name='referralmedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='update',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='update',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.case'),
        ),
    ]
