# Generated by Django 4.2.16 on 2025-08-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_populate_default_badges"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["category", "required_cases"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="communitygoal",
            options={
                "ordering": ["-is_featured", "-created_at"],
                "verbose_name": "Community Goal",
                "verbose_name_plural": "Community Goals",
            },
        ),
        migrations.AlterModelOptions(
            name="emailanalytics",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email Analytics",
                "verbose_name_plural": "Email Analytics",
            },
        ),
        migrations.AlterModelOptions(
            name="emailschedule",
            options={
                "ordering": ["scheduled_for"],
                "verbose_name": "Email Schedule",
                "verbose_name_plural": "Email Schedules",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="storycomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Story Comment",
                "verbose_name_plural": "Story Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="storylike",
            options={
                "verbose_name": "Story Like",
                "verbose_name_plural": "Story Likes",
            },
        ),
        migrations.AlterModelOptions(
            name="storymedia",
            options={
                "verbose_name": "Story Media",
                "verbose_name_plural": "Story Media",
            },
        ),
        migrations.AlterModelOptions(
            name="userbadge",
            options={
                "ordering": ["-earned_at"],
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerstory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Volunteer Story",
                "verbose_name_plural": "Volunteer Stories",
            },
        ),
    ]
