version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=snda_user
      - POSTGRES_PASSWORD=snda
      - POSTGRES_DB=snda_db
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=snda
    depends_on:
      - db

volumes:
  postgres_data:
