[build]
  publish = "frontend/.next"
  command = "cd frontend && npm run build"

[functions]
  external_node_modules = ["next"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "https://snda-backend.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://snda-backend.railway.app"
  NEXT_PUBLIC_FRONTEND_URL = "https://snda-platform.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://snda-backend.railway.app"
  NEXT_PUBLIC_FRONTEND_URL = "$DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://snda-backend.railway.app;"
