# 🚀 sNDa Backend - Render Blueprint
# Production-ready configuration for complete sNDa platform deployment

services:
  # 🌐 Main Web Application
  - type: web
    name: snda-backend
    runtime: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /api/health/
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "snda-backend.onrender.com,snda-platform.netlify.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://snda-platform.netlify.app"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"

  # 🔴 Redis Cache & Celery Broker
  - type: redis
    name: snda-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # 👷 Celery Background Worker
  - type: worker
    name: snda-celery-worker
    runtime: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker -l info --concurrency=1 --max-tasks-per-child=1000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        sync: false

  # ⏰ Celery Beat Scheduler
  - type: worker
    name: snda-celery-beat
    runtime: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        sync: false

# 🗄️ Database Configuration
databases:
  - name: snda-db
    databaseName: snda
    user: snda_user
    plan: free
