# 🚀 sNDa Backend Deployment Configuration (Render)
# Production-ready configuration for Django backend with full services

services:
  # 🌐 Main Web Application
  - type: web
    name: snda-backend
    runtime: python
    plan: free
    pythonVersion: "3.12"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py create_default_badges
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    healthCheckPath: /api/health/
    autoDeploy: true
    envVars:
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      
      # Cache & Queue
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      
      # Django Configuration
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "snda-backend.onrender.com,snda.netlify.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://snda.netlify.app"
      
      # Security
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      
      # Email Configuration (SendGrid)
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@snda.netlify.app"
      
      # Stripe Configuration
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      
      # Application Settings
      - key: FRONTEND_URL
        value: "https://snda.netlify.app"
      - key: BACKEND_URL
        value: "https://snda-backend.onrender.com"

  # 🔄 Celery Worker
  - type: worker
    name: snda-celery-worker
    runtime: python
    plan: free
    pythonVersion: "3.12"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: celery -A config worker -l info --concurrency=2
    autoDeploy: true
    envVars:
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      
      # Cache & Queue
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      
      # Django Configuration
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      
      # Email Configuration
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@snda.netlify.app"

  # 📅 Celery Beat Scheduler
  - type: worker
    name: snda-celery-beat
    runtime: python
    plan: free
    pythonVersion: "3.12"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: celery -A config beat -l info
    autoDeploy: true
    envVars:
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: snda-db
          property: connectionString
      
      # Cache & Queue
      - key: REDIS_URL
        fromService:
          type: redis
          name: snda-redis
          property: connectionString
      
      # Django Configuration
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  # 🗄️ PostgreSQL Database
  - name: snda-db
    databaseName: snda_production
    user: snda_user
    plan: free

services:
  # 🔴 Redis Cache & Celery Broker
  - type: redis
    name: snda-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []